config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'levels' => "levels#index"
  get 'levels/list' => 'levels#list'
  get 'levels/new' => 'levels#new'
  post 'levels' => 'levels#create'
  get 'levels/:id/item' => 'levels#item', as: :levels_item
  get 'levels/:id' => "levels#show", as: :level
  get 'levels/:id/edit' => 'levels#edit', as: :edit_level
  patch 'levels/:id' => 'levels#update'
  delete 'levels/:id' => 'levels#destroy'

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'sessions' => "sessions#destroy"

  get 'pages/loggedin' => "pages#loggedin"
  get 'pages' => "pages#index"

  get 'signup' => "users#new"
  post 'users' => "users#create"
  get 'users/:id' => "users#show", as: :profile
  get 'users/:id/edit' => "users#edit", as: :edit_user
  patch 'users/:id' => "users#update", as: :user
  delete 'users/:id' => "users#destroy"

  post 'user/scores' => "scores#create"

  match 'auth/:provider/callback', to: 'sessions#create_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy_facebook', as: 'signout', via: [:get, :post]

end

app/views/pages/index.html.erb
<div class="text-block">

  <h1 class="brand-title">Colemak'd</h1>

  <%= link_to "Sign Up", signup_path, class: "main-image-button my-button" %>
  <span class="sign-in">or <strong><%= link_to "Sign In", login_path %></strong></span>
    <div class="image-wrapper">
      <%= image_tag 'workstation.jpg', class: "index-image" %>
    </div>
  </div>

<div class="intro-box">
  <div class="row">
    <div class="medium-10 medium-offset-1 columns">
      <h1>Step up your typing game</h1>

      <p><span class="list-letter list-letter a">A</span><span class="sub-text">Colemak'd makes it easy to learn the Colemak keyboard.  Already a pro? Check out our challenge levels and compete for a spot on the leaderboard!</span></p>

    </div>
  </div>
</div>

<div class="about-colemak-box">
  <div class="row">
    <div class="medium-10 medium-offset-1 columns">
          <h1>Making typing fun</h1>
          <p>
            <span class="sub-text">
              <div class="row">
                <div class="large-5 large-offset-5 small-9 columns">
                  <p>Levels are short and simple.</p>
                  <p>Your highest scores are always recorded so you can easily chart your progress.</p>
                </div>
                <div class="medium-1 small-3 columns">
                  <span class="list-letter list-letter a">B</span>
                </div>
              </div>
            </span>
          </p>
    </div>
  </div>
</div>

<div class="benefit-colemak-box">
  <div class="row">
    <div class="medium-10 medium-offset-1 columns">
    <span class="list-letter list-letter a">C</span>
          <h1>The Benefits of Colemak</h1>
    </div>
  </div>


  <div class="row contain-row">

    <div class="medium-3 columns">
      <p><i class="fi-plus icon"></i></p>
      <p class="small-header">Ergonomic</p>
      <p class="small-text">Your fingers on QWERTY move 2.2x more than on Colemak, increasing your chance of developing RSSIs.</p>
    </div>
    <div class="medium-3 columns">
      <p><i class="fi-clock icon"></i></p>
      <p class="small-header">Fast</p>
      <p class="small-text">Most of the typing is done on the strongest and fastest fingers, Lowering your same-finger ratio.</p>
    </div>

    <div class="medium-3 columns">
      <p><i class="fi-puzzle icon"></i></p>
      <p class="small-header">Easy</p>
      <p class="small-text">There is only 17 keys that have been remapped as opposed to Dvorak, another alternative keyboard's 33.
    </div>

    <div class="medium-3 columns">
      <p><i class="fi-dollar icon"></i></p>
      <p class="small-header">Free</p>
      <p class="small-text">The Colemak keyboard layout is free software released under the public domain</p>
    </div>

  </div>

</div>

<div class="newsletter-box">
  <div class="row">
    <div class="small-10 small-offset-1 columns newsbox">
      <form>
      <fieldset>
      <legend><h3>Sign Up for our newsletter!</h3></legend>
        <div class="large-6 large-offset-3 columns">
          <div class="row collapse postfix-radius">
            <div class="small-9 columns">
              <input type="text" placeholder="Enter Your Email">
            </div>
            <div class="small-3 columns">
              <span class="postfix">Go!</span>
            </div>
          </div>
        </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>

app/views/pages/loggedin.html.erb
<div class="header">
  <div class="row">
    <div class="large-12 columns">
      <h2>Welcome <%= current_user.username || current_user.name %>!</h2>
    </div>
  </div>
</div>


<div class="row">


  <div class="large-8 columns">
    <div class="scores">
    <h3>Top 10 Scores:</h3>
    <table>
      <thead>
        <tr>
          <th width="150">Player</th>
          <th width="100">Score</th>
          <th>Level</th>
          <th width="100">Date</th>
        </tr>
      </thead>
      <tbody><% @top_scores.each do |score| %>
        <tr>
          <td><%= User.find(score.user_id).username || User.find(score.user_id).name %></td>
          <td><%= score.wpm %> WPM</td>
          <td><%= link_to Level.find(score.level_id).name, level_path(Level.find(score.level_id)) %></td>
          <td><%= score.short_date_added %></td>
        </tr>
        <%end %>
      </tbody>
    </table>
    </div>
  </div>

  <div class="large-4 columns">

      <%= link_to levels_path do %>
          <div class="visit-level">
            <p>Levels</p>
            <p><i class="fi-fast-forward"></i></p> 
          </div>
      <% end %>

  </div>

</div>