config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'levels' => "levels#index"
  get 'levels/list' => 'levels#list'
  get 'levels/new' => 'levels#new'
  post 'levels' => 'levels#create'
  get 'levels/:id/item' => 'levels#item', as: :levels_item
  get 'levels/:id' => "levels#show", as: :level
  get 'levels/:id/edit' => 'levels#edit', as: :edit_level
  patch 'levels/:id' => 'levels#update'
  delete 'levels/:id' => 'levels#destroy'

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'sessions' => "sessions#destroy"

  get 'pages/loggedin' => "pages#loggedin"
  get 'pages' => "pages#index"

  get 'signup' => "users#new"
  post 'users' => "users#create"
  get 'users/:id' => "users#show", as: :profile
  get 'users/:id/edit' => "users#edit", as: :edit_user
  patch 'users/:id' => "users#update", as: :user
  delete 'users/:id' => "users#destroy"

  post 'user/scores' => "scores#create"

  match 'auth/:provider/callback', to: 'sessions#create_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy_facebook', as: 'signout', via: [:get, :post]

end

app/models/level.rb
class Level < ActiveRecord::Base


  has_many :scores, dependent: :destroy
  belongs_to :category

  validates :content, presence: true, length: { in: 30.. 80 }
  validates :name, presence: true, uniqueness: true


  accepts_nested_attributes_for :category



  def next
    Level.where("id > ?", self.id).order("id ASC").first
  end

  def prev
    Level.where("id < ?", self.id).order("id DESC").first
  end


end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :require_user

  before_action :require_admin, only: [:new, :edit]

  def index
    @categories = Category.all
  end

  def show
    @level = Level.find(params[:id])

    l_id = params[:id]

    if defined? current_user.scores.where(level_id: l_id).first.wpm
      @old_score = current_user.scores.where(level_id: l_id).first.wpm
    else
      @old_score = nil
    end

  end

  def new
    @level = Level.new
    @level.category = Category.new
  end


  def create
    @level = Level.new(level_params)
    @categories = Category.all
    if @level.save
      flash[:success] = "Your level has been created!"
      redirect_to levels_item_path(@level)
    else
      flash[:alert] = @level.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @level = Level.find(params[:id])
  end

  def list
    @categories = Category.all
  end

  def item
    @level = Level.find(params[:id])
    @category = Category.find(@level.category_id)
  end

  def update
    @level = Level.find(params[:id])
    if @level.update_attributes(level_params)
      flash[:success] = "Your level has been updated!"
      redirect_to levels_item_path(@level)
    else
      flash[:alert] = @level.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def destroy
    flash[:alert] = "Your level has been deleted!"
    @level = Level.find(params[:id])
    @level.destroy
    redirect_to levels_list_path
  end


  private

  def level_params
    params.require(:level).permit(:name, :content, :content2, :content3, :content4, :content5, :category_id, category_attributes: [:name])
  end

end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/edit.html.erb
<div class="row">
  <div class="large-12 columns header">
     <h1>Edit a level</h1>
  </div>
</div>
<div class="row">
  <div class="large-10 large-offset-1 columns">

  <%= form_for @level do |f| %>
    <p>Name: <%= f.text_field :name %></p>
    <p>First line: <%= f.text_field :content %></p>
    <p>Second line: <%= f.text_field :content2 %></p>
    <p>Third line: <%= f.text_field :content3 %></p>
    <p>Fourth line: <%= f.text_field :content4 %></p>
    <p>Fifth line: <%= f.text_field :content5 %></p>
    <%= f.submit "Save Changes", class: "button small secondary" %>
    <%= link_to "Delete level", @level, method: :delete, data: {confirm: "Are you sure you want to delete this level?"}, class: "button small" %>

  <% end %>

  <%= link_to "Back to Levels List", levels_list_path %>

  </div>
</div>

app/views/levels/index.html.erb
<div class="levels-wrapper">
  <div class="levels-header">
    <div class="row">
      <div class="large-8 large-offset-2 medium-10 medium-offset-1 columns">
        <h3>Choose a level below to get started...</h3>
      </div>
    </div>
  </div>

  <% @categories.each do |category| %>
    <% unless category.levels.empty? %>
      <ul class="accordion panel-square" data-accordion>
        <li class="accordion-navigation">
          <a class="panel-square-header" href="#cat<%=category.id%>"><h3><%= category.name %></h3><div class="arrow-down"></div></a>
           <div id="cat<%=category.id%>" class="content panel-square-body">
          <% category.levels.each do |level| %>


            <%= link_to level_path(level) do %>
              <div class="level-button">
              <%= level.name %>
              </div>
            <% end %>

          <% end %>
        </div>
      </li>
    </ul>

    <% end %>
  <% end %>


</div>

app/views/levels/item.html.erb
<div class="row">
  <div class="large-12 columns header">
    <div class="panel">
      <h2><%= @level.name %></h2>
    </div>

    <table>
      <tbody>
        <tr>
          <td><strong>Category</strong></td>
          <td><%= @category.name %></td>
        </tr>
        <tr>
          <td><strong>Line 1</strong></td>
          <td><%= @level.content %></td>
        </tr>
        <% if @level.content2.to_s != "" %>
          <tr>
            <td><strong>Line 2</strong></td>
            <td><%= @level.content2 %></td>
          </tr>
        <% end %>
            <% if @level.content3.to_s != "" %>
          <tr>
            <td><strong>Line 3</strong></td>
            <td><%= @level.content3 %></td>
          </tr>
        <% end %>
        <% if @level.content4.to_s != "" %>
          <tr>
            <td><strong>Line 4</strong></td>
            <td><%= @level.content5 %></td>
          </tr>
        <% end %>
            <% if @level.content5.to_s != "" %>
          <tr>
            <td><strong>Line 5</strong></td>
            <td><%= @level.content5 %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <ul class="button-group round">
      <li><%= link_to "Edit Level", edit_level_path(@level), class: "button small" %></li>
      <li><%= link_to "Delete level", @level, method: :delete, data: {confirm: "Are you sure you want to delete this level?"}, class: "button small" %></li>
      <li><%= link_to "Back to Levels List", levels_list_path, class: "button small" %></li>
    </ul>
  </div>
</div>

app/views/levels/list.html.erb
<div class="row">
<div class="large-12 columns header">
<h1>List of Levels</h1>
</div>
</div>

<div class="row">
<div class="large-12 columns">
<% @categories.each do |category| %>
<% unless category.levels.empty? %>
    <h3><%= category.name %></h3>
    <% category.levels.each do |level| %>
<table>
  <thead>
    <tr>
      <th width="200">Name</th>
      <th width="500">Content</th>
      <th width="150"></th>
      <th width="150"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= link_to level.name, levels_item_path(level) %></td>
      <td><%= truncate(level.content, :length => 60) %>...</td>
      <td><%= link_to "Edit Level", edit_level_path(level), class: "button small" %></td>
      <td><%= link_to "Delete level", @level, method: :delete, data: {confirm: "Are you sure you want to delete this level?"}, class: "button small" %></td>
    </tr>
      <%end %>
    <% end %>
  </tbody>
</table>
<% end %>
</div>
</div>

app/views/levels/new.html.erb
<div class="row">
  <div class="large-12 columns header">
    <h1>Add a new level</h1>
  </div>
</div>
<div class="row">
	<div class="large-10 large-offset-1 columns">
		<% if @level.errors.full_messages.any? %>
			<% @level.errors.full_messages.each do |error_message| %>
				<%= error_message if @level.errors.full_messages.first == error_message %> <br />
			<% end %>

		<% end %>

		<%= form_for @level do |f| %>
			<p>Name: <%= f.text_field :name %></p>
			<p>Category: </p>
			<div id="formGroup">
				<%= f.collection_select(:category_id, Category.all, :id, :name, prompt: true)%>

				<span id="newCatText">Add a new Category: </span><%= f.fields_for :category do |cat_form| %>
				     <%= cat_form.text_field :name %>
				<% end %>
			</div>
			<p>First line: <%= f.text_field :content %></p>
			<p>Second line: <%= f.text_field :content2 %></p>
			<p>Third line: <%= f.text_field :content3 %></p>
			<p>Fourth line: <%= f.text_field :content4 %></p>
			<p>Fifth line: <%= f.text_field :content5 %></p>
			<%= f.submit "Add level", class: "button small" %>

		<% end %>

		<%= link_to "Back to Levels List", levels_list_path %>
	</div>
</div>

app/views/levels/show.html.erb
<div class="top-header">
	<div class="row">
		<div class="large-8 columns">
			<h2><%= @level.name %></h2>
		</div>
		<div class="large-4 columns return">
			<%= link_to levels_path do %>
				<i class="fi-arrow-left"></i>  Return to Levels
			<% end %>
		</div>
	</div>
</div>


<div class="game-wrapper">

	<div class="gamecontainer">

		<div class="box-wrapper">
			<div class="exercise-box" id="exerciseBox"><%= @level.content %></div>
			<div class="input-wrapper">
				<div class="input-box" id="inputBox">
				</div>
				<div class="hidden-box" id="hiddenBox">
				</div>
			</div>
		</div>

		<% if @level.content2.to_s != "" %>
			<div class="box-wrapper">
				<div class="exercise-box" id="exerciseBox2"><%= @level.content2 %></div>
				<div class="input-wrapper">
					<div class="input-box" id="inputBox2">
					</div>
					<div class="hidden-box" id="hiddenBox2">
					</div>
				</div>
			</div>
		<% end %>

		<% if @level.content3.to_s != "" %>
			<div class="box-wrapper">
				<div class="exercise-box" id="exerciseBox3"><%= @level.content3 %></div>
				<div class="input-wrapper">
					<div class="input-box" id="inputBox3">
					</div>
					<div class="hidden-box" id="hiddenBox3">
					</div>
				</div>
			</div>
		<% end %>

		<% if @level.content4.to_s != ""  %>
			<div class="box-wrapper">
				<div class="exercise-box" id="exerciseBox4"><%= @level.content4 %></div>
				<div class="input-wrapper">
					<div class="input-box" id="inputBox4">
					</div>
					<div class="hidden-box" id="hiddenBox4">
					</div>
				</div>
			</div>
		<% end %>

		<% if @level.content5.to_s != ""  %>
			<div class="box-wrapper">
				<div class="exercise-box" id="exerciseBox5"><%= @level.content5 %></div>
				<div class="input-wrapper">
					<div class="input-box" id="inputBox5">
					</div>
					<div class="hidden-box" id="hiddenBox5">
					</div>
				</div>
			</div>
		<% end %>

	</div>

<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">

	<h2 id="modalTitle">Good job!</h2>
	<p class="lead" id="modalWpm"></p>
	<% if @old_score %>
	<p>Your previous top score: <%= @old_score %></p>
	<% end %>
		<%= form_for [current_user, Score.new] do |f| %>
			<%= f.hidden_field :level_id, :value => @level.id %>
			<%= f.hidden_field :wpm, id: 'WpmBox' %>
			<%= f.submit "Try Again?", class: "small button" %>
			<% if @level.next %>
			<%= f.submit "Next Level", class: "small button" %>
			<% end %>
			<%= f.submit "Back to Levels", class: "small button" %>
		<% end %>
	
	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>