config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'levels' => "levels#index"
  get 'levels/list' => 'levels#list'
  get 'levels/new' => 'levels#new'
  post 'levels' => 'levels#create'
  get 'levels/:id/item' => 'levels#item', as: :levels_item
  get 'levels/:id' => "levels#show", as: :level
  get 'levels/:id/edit' => 'levels#edit', as: :edit_level
  patch 'levels/:id' => 'levels#update'
  delete 'levels/:id' => 'levels#destroy'

  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'sessions' => "sessions#destroy"

  get 'pages/loggedin' => "pages#loggedin"
  get 'pages' => "pages#index"

  get 'signup' => "users#new"
  post 'users' => "users#create"
  get 'users/:id' => "users#show", as: :profile
  get 'users/:id/edit' => "users#edit", as: :edit_user
  patch 'users/:id' => "users#update", as: :user
  delete 'users/:id' => "users#destroy"

  post 'user/scores' => "scores#create"

  match 'auth/:provider/callback', to: 'sessions#create_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy_facebook', as: 'signout', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Typingapp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Colemak'd", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if current_user %>
      <li class="has-dropdown">
        <%= link_to current_user.username || current_user.name, profile_path(current_user)  %>
        <ul class="dropdown">
          <li><%= link_to "Profile", edit_user_path(current_user)  %></li>
          <li><%= link_to "My High Scores", profile_path(current_user)  %></li>
          <li><%= link_to "Logout", sessions_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
          <li><%= link_to "Login", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
      <% end %>
    </ul>

    <ul class="left">
      <li><%= link_to "Home", pages_loggedin_path %></li>
      <% if current_user %>
        <li><%= link_to "Levels", levels_path %></li>
        <% if current_user.admin? %>
          <li><%= link_to "Admin Levels List", levels_list_path %></li>
          <li><%= link_to "Add New Level", levels_new_path %></li>
        <% end %>
    <% end %>
    </ul>
  </section>
</nav>

  </div>
  <% flash.each do |key, value| %>
    <div data-alert class="alert-box <%=key %> radius">
      <%= value %>
    <a href="#" class="close">&times;</a>
    </div>
  <% end %>


  <div class="wrapper">
    <%= yield %>
    <br>
    <%#= params %>
  </div>

<div class="footer">
  <div class="row">
    <div class="small-12 columns">
    &copy; Colemak'd. All rights reserved. 
    </div>
  </div>
</div>

  
 </body>
</html>